FROM openjdk:17.0.1-jdk-slim

LABEL maintainer="GuBee"
LABEL version="1.0"

ENV DB_NAME="postgres"
ENV DB_HOSTNAME="postgres"
ENV DB_PORT="5432"
ENV DB_USERNAME="gubee"
ENV DB_PWD="gubee"

EXPOSE 8080

COPY core/target/gubee-interview.jar interview.jar

# debug ENTRYPOINT [ "java" , "-Xms128m",  "-Xmx400m", "-agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=y", "-jar", "-DLog4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector", "interview.jar", "--jdbc.url=jdbc:postgresql://postgres:5432/postgres", "--jdbc.password=gubee", "--jdbc.username=gubee"]
ENTRYPOINT [ "java" , "-Xms128m",  "-Xmx400m", "-jar", "-DLog4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector", "interview.jar", "--jdbc.url=jdbc:postgresql://postgres:5432/postgres", "--jdbc.password=gubee", "--jdbc.username=gubee"]